### ISSUE TITLE
Doesn't work with latest electron

### ISSUE THREAD

**Issue by tom-james-watson** [CharlieHess/node-mac-notifier#10]
Just on importing the module I receive the following error:

```
objc[35839]: Class NotificationCenterDelegate is implemented in both /Users/tomw/git/artpip-app/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework and /Users/tomw/git/artpip-app/node_modules/node-mac-notifier/build/Release/Notification.node. One of the two will be used. Which one is undefined.
App threw an error during load
Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/tomw/git/artpip-app/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/tomw/git/artpip-app/node_modules/node-mac-notifier/index.js:5:44)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tomw/git/artpip-app/app/windows.js:12:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tomw/git/artpip-app/app/background.js:15:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tomw/git/artpip-app/app/main.js:22:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at loadApplicationPackage (/Users/tomw/git/artpip-app/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:288:12)
    at Object.<anonymous> (/Users/tomw/git/artpip-app/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:330:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Object.<anonymous> (/Users/tomw/git/artpip-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:173:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:360:7)
    at startup (bootstrap_node.js:152:9)
    at bootstrap_node.js:479:3
```

Any idea?

Thanks!

**Comment by bengotow** [comment]
Hey folks - `Module version mismatch` is thrown when the native code in a node module is compiled for your system instead of the version of Electron you're using. You most likely just need to use something like https://github.com/electron/electron-rebuild.

**Comment by ccnokes** [comment]
It works for me on 1.4.5. 

Another way to compile is:
```
cd ./node_modules/node-mac-notifier
HOME=~/.electron-gyp node-gyp rebuild --target=1.4.5 --arch=x64 --dist-url=https://atom.io/download/electron
```
You have to have node-gyp installed globally first though. Electron-rebuild is easier but here's another option.

**Comment by CharlieHess** [comment]
@bengotow is correct!
